SELECT 
    cedula,
    genero,
    nombre_y_apellido,
    fechanacimiento,
    placa,
    codmunicipio,
    nommunicipio,
    coddpto,
    nomdepto,
    direccion,
    IF(telefono1 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono1, NULL) AS telefono1,
    IF(telefono2 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono2, NULL) AS telefono2,
    IF(telefono3 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono3, NULL) AS telefono3,
    IF(telefono_4 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono_4, NULL) AS telefono_4,
    Fecha_Inicio_Vigencia,
    modelo,
    linea,
    motor,
    chasis,
    cod_fasecolda,
    marca,
    marca_y_linea,
    tasa,
    suma_asegurada,
    aseguradora_actual,
    clase_vehiculo,
    servicio,
    email,
    N_Temporario,
    Prima,
    Prima_Sin_Iva,
    tipo_base,
    nombre_bd_original,
    segmento_base,
    fecha_cargue,
    fecha_recotizada,
    fecha_asignacion,
    fecha_ini_gestion,
    fecha_fin_gestion,
    ano_asignacion,
    mes_asignacion,
    calificacion
FROM
    bbdd_cos_bog_grupo_axa.tb_asignacion_coomeva_cartera_v2