SELECT 
    co_id,
    anio,
    registro,
    periodo,
    nombre_base,
    fecha_asignacion,
    genero,
    nombre,
    segundo_nombre,
    apellido,
    segundo_apellido,
    CONCAT(nombre, ' ', segundo_nombre, ' ', apellido, ' ', segundo_apellido) AS nombre_completo,
    fecha_nacimiento,
    email,
    cod_departamento,
    departamento,
    cod_municipio,
    municipio,
    direccion,
    IF(telefono1 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono1, NULL) AS telefono1,
    IF(telefono2 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono2, NULL) AS telefono2,
    IF(telefono3 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono3, NULL) AS telefono3,
    IF(telefono4 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono4, NULL) AS telefono4,
    IF(telefono5 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono5, NULL) AS telefono5,    
    placa,
    modelo,
    linea,
    motor,
    chasis,
    cod_fasecolda,
    marca,
    marca_y_linea,
    clase_vehiculo,
    servicio,
    aseguradora_actual,
    fecha_fin_vigencia_actual,
    DATE_FORMAT(fecha_fin_vigencia_actual, '%%Y%%m') AS periodo_vig,
    tasa,
    suma_asegurada,
    no_temporario_plus,
    prima_temporario_plus,
    prima_temporario_sin_iva_plus,
    no_temporario_tradicional,
    prima_tradicional,
    prima_tradicional_sin_iva,
    no_temporario_vip,
    prima_temporario_vip,
    prima_temporario_vip_sin_iva,
    no_temporario_nuevo_vip,
    prima_nueva_vip,
    prima_nueva_vip_sin_iva,
    no_temporario_esencial,
    prima_temporario_esencial,
    prima_temporario_esencial_sin_iva,
    no_temporario_nuevo_esencial,
    prima_nueva_esencial,
    prima_nueva_esencial_sin_iva,
    grupos_1_y_2,
    segmentacion_grupo_1_y_2_final,
    prioridad
FROM
    bbdd_cos_bog_grupo_axa.tb_asignacion_falabella_v2
		WHERE periodo = DATE_FORMAT('2025-09-01','%%Y%%m')