SELECT 
    placa,
    anio,
    cedula,
    genero,
    nombre_y_apellido,
    fechanacimiento,
    codmunicipio,
    nommunicipio,
    coddpto,
    nomdepto,
    direccion,
    IF(telefono1 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono1, NULL) AS telefono1,
    IF(telefono2 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono2, NULL) AS telefono2,
    IF(telefono3 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono3, NULL) AS telefono3,
    IF(telefono_4 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono_4, NULL) AS telefono_4,
    fecha_fin_vigencia_actual,
    modelo,
    linea,
    motor,
    chasis,
    cod_fasecolda,
    marca,
    marca_y_linea,
    tasa,
    suma_asegurada,
    aseguradora_actual,
    clase_vehiculo,
    servicio,
    email,
    no_temporario_plus_plus,
    prima_plus_plus,
    prima_sin_iva_plus_plus,
    no_temporario_vip_vip,
    prima_vip_vip,
    prima_sin_iva_vip_vip,
    no_temporario_tradicional_vip,
    prima_tradicional_vip,
    prima_sin_iva_tradicional_vip,
    no_temporario_esencial_esencial,
    prima_esencial_esencial,
    prima_sin_iva_esencial_esencial,
    no_temporario_esencial_esencial_1,
    prima_esencial_esencial_1,
    prima_sin_iva_esencial_esencial_1,
    no_temporario_esencial_esencial_2,
    prima_esencial_esencial_2,
    prima_sin_iva_esencial_esencial_2,
    grupo_perfil,
    fecha_asignacion,
    periodo,
    nombre_base,
    hoja
FROM
    bbdd_cos_bog_grupo_axa.tb_asignacion_coomeva_v2
    WHERE periodo >= DATE_FORMAT('2025-01-01', '%%Y%%m');
    