select 
	`apellido-23` AS Apellido,
	apellido2 AS 'Apellido 2',
    nombre4 AS Nombre,
    `tn-documento7` AS placa,
    `afecha-de-nacimiento7` AS 'Fecha de Nacimiento',
    direcciona8 AS 'Dirección',
    `tn-telefono12` AS 'T-N° Télefono',
    `tnumero-celular13` AS 'T-Número Celular',
    aemail111 AS 'T-E-mail',
    `nombre-de-la-franquicia16` AS 'Nombre de la franquicia',
    `departamento19` AS 'Departamento',
    municipios37 AS 'Ciudad',
    `client_new_id` AS 'T-N° Documento',
    `vigencia-de-la-poliza1` AS 'Vigencia de la Poliza',
    `valor-asegurado2` AS 'Valor Asegurado',
    `n-temporario-plus3` AS 'N° Temporario Plus',
    `prima-plus4` AS 'Prima Plus',
    `modelo-0` AS 'Modelo',
    `linea-1` AS 'Línea',
    motor2 AS 'Motor',
    chasis3 AS 'Chasis',
    `cod-fasecolda4` AS 'Cod Fasecolda',
    marca5 AS 'Marca'
FROM bbdd_cos_bog_grupo_axa.tb_soul2_501_axa_renovaciones_scotiabanck;
