SELECT 
    codid,
    anio,
    periodo,
    nombre_base,
    fecha_asignacion,
    typeid,
    primer_nombre,
    segundo_nombre,
    primer_apellido,
    segundo_apellido,
    CONCAT(primer_nombre, ' ', segundo_nombre, ' ', primer_apellido, ' ', segundo_apellido) AS nombre_completo,
    genero,
    fechadenacimiento,
    edad,
    antig_edad_segmento,
    email,
	IF(tel1 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', tel1, NULL) AS tel1,
	IF(tel2 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', tel2, NULL) AS tel2,
	IF(tel3 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', tel3, NULL) AS tel3,
	IF(tel4 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', tel4, NULL) AS tel4,
	IF(tel5 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', tel5, NULL) AS tel5,
	IF(tel6 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', tel6, NULL) AS tel6,
	IF(tel7 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', tel7, NULL) AS tel7,
	IF(tel8 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', tel8, NULL) AS tel8,
    coddpto,
    nomdepto,
    codmunicipio,
    nommunicipio,
    direccion,
    prioridad,
    segcal,
    numpro,
    opty_id,
    id_campana,
    cod_canal,
    tipo_producto,
    nombre_franquicia,
    fecha_vencimiento_tarjeta,
    cupo_hoy,
    cupo_disponible,
    codigo_agrupador,
    placa,
    modelo,
    linea,
    motor,
    chasis,
    cod_fasecolda,
    marca,
    clase_vehiculo,
    servicio,
    No_de_vehiculos,
    aseguradora_actual,
    asistencia,
    valor_asegurado,
    esencial,
    no__temporario_plus,
    prima_plus,
    iva,
    fecha,
    fecha_fin_vigencia_actual,
    fecha_inicio_nueva_vigencia
FROM
    bbdd_cos_bog_grupo_axa.tb_asignacion_scotiabank_v2
    WHERE periodo = DATE_FORMAT('2025-07-01', '%%Y%%m')