SELECT 
    contrato,
    periodo,
    anio,
    fecha_asignacion,
    mes_de_gestion,
    solicitud_no,
    sucursal,
    regional,
    asesor,
    clave,
    director,
    clave_director,
    tipo,
    plan,
    cruce_domiciliacion,
    frecuencia_de_pago,
    fecha_inicio,
    fecha_fin,
    CONCAT(fecha_inicio, fecha_fin) AS llave_fecha_ini_fin,
    nombre_colectivo,
    tipo_identificacion,
    no_identificacion_colectivo,
    tipo_identificacion_contrante,
    no_identificacion_contrante,
    nombres,
    parentesco,
    correo_electronico,
    IF(celular REGEXP '^(3[0-9]{9}|60[0-9]{8})$', celular, NULL) AS celular,
    IF(celular_1 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', celular_1, NULL) AS celular_1,
    IF(telefono_correspondencia REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono_correspondencia, NULL) AS telefono_correspondencia,
    direccion_correspondencia,
    ciudad_correspondencia,
    cod_ciudad_correspondencia,
    nombre_base,
    hoja
FROM
    bbdd_cos_bog_grupo_axa.tb_asignacion_bienvenida_tradicional_v2
    WHERE periodo = DATE_FORMAT('2025-10-01', '%%Y%%m')