SELECT 
    cedula,
    anio,
    periodo,
    nombre_base,
    fecha_asignacion,
    genero,
    nombre_y_apellido,
    fecha_nacimiento,
    email,
    cod_dpto,
    nom_depto,
    cod_municipio,
    nom_municipio,
    direccion,
    IF(telefono1 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono1, NULL) AS telefono1,
    IF(telefono2 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono2, NULL) AS telefono2,
    IF(telefono3 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono3, NULL) AS telefono3,
    IF(telefono_4 REGEXP '^(3[0-9]{9}|60[0-9]{8})$', telefono_4, NULL) AS telefono_4,
    placa,
    modelo,
    linea,
    motor,
    chasis,
    cod_fasecolda,
    marca,
    marca_y_linea,
    clase_vehiculo,
    servicio,
    aseguradora_actual,
    fecha_fin_vigencia_actual,
    DATE_FORMAT(fecha_fin_vigencia_actual, '%%Y%%m') AS periodo_vig,
    tasa,
    suma_asegurada,
    no_temporario_plus_plus,
    prima_plus_plus,
    prima_sin_iva_plus_plus,
    no_temporario_plus_vip,
    prima_plus_vip,
    prima_sin_iva_plus_vip,
    no_temporario_moto_plus,
    prima_moto_plus,
    prima_sin_iva_moto_plus,
    no_temporario_moto_esencial,
    prima_moto_esencial,
    prima_sin_iva_moto_esencial,
    perfil,
    perfil_2,
    observaciones_1,
    observaciones_2
FROM
    bbdd_cos_bog_grupo_axa.tb_asignacion_fincomercio_v2
    WHERE periodo = DATE_FORMAT('2025-09-01', '%%Y%%m');